Initial commit
y-scope/clp-ffi-py pull request #1
Opened 2023-05-27 05:33 UTC by LinZhihao-723

This first PR constructs the project structure of clp-ffi-py. It structures the src files and sets up necessary build tools. Currently, only 4-byte encoding methods are implemented (which is used by clp-loglib-py). We can incrementally port other methods later.

2023-06-01 22:05 UTC, davidlion requested changes

2023-06-01 22:05 UTC, davidlion commented on README.md
> +This module provides Python packages to interface with [CLP Core Features](https://github.com/y-scope/clp/tree/main/components/core) through CLP's FFI (foreign function interface). Currently, this li
Shorten long lines by using semantic line feeds (https://rhodesmill.org/brandon/2012/one-sentence-per-line/) and references (https://www.markdownguide.org/basic-syntax#reference-style-links)

2023-06-04 18:28 UTC, kirkrodrigues commented on README.md
> +To maually build a package for distribution, run the following step. It should generate both .tar.gz pacakge and .whl package under `./dist/`.
* maually -> manually
* pacakge -> package

2023-06-04 18:28 UTC, kirkrodrigues commented on README.md
> +   `python3.8 -m venv venv; . ./venv/bin/activate`
* `python3.8` -> `python3`?
* If we want to do these commands in one line, it should really be `&&` instead of `;`, right?

2023-06-04 18:28 UTC, kirkrodrigues commented on README.md
Personally, I prefer putting commands that users need to copy in a code **block** rather than an **inline** code snippet.
E.g.

Code block:

```shell
python3 -m venv venv
```

Inline code: `python3 -m venv venv`

It's faster to copy the former since you just need to copy the entire line. Moreover, GitHub's Markdown renderer creates a copy button for code blocks making it even easier.

2023-06-04 18:28 UTC, kirkrodrigues commented on README.md
> +   `pip install -r requirements-dev.txt`
Can we use dev dependencies in the toml rather than a requirements.txt file?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/ErrorMessage.hpp
> +#ifndef CLP_PY_ERROR_MESSAGE
```suggestion
#ifndef CLP_FFI_PY_ERROR_MESSAGE
```

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/ErrorMessage.hpp
> +namespace clp_ffi_py::ErrorMessage::Encoding {
Can we move this nested namespace into the previous namespace?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +         "encode the preamble with a reference timestamp, a timestamp format, and a time zone."},
I was reading a bit about how these work and this is actually where we should be putting the docstrings that are currently in `CLPFourByteEncoder.pyi`. There are two caveats:
* We need to specify the method's signature at the top of the method followed by `--\n\n`. See [here](https://stackoverflow.com/questions/1104823/python-c-extension-method-signatures-for-documentation) for more details.
* We should use the [`PyDoc_STRVAR`](https://docs.python.org/3/c-api/intro.html#c.PyDoc_STRVAR) macro.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +        {NULL, NULL, 0, NULL}};
* Can we use `nullptr` instead or can we rely on [zero initialization](https://en.cppreference.com/w/cpp/language/zero_initialization)?
* Given the length of this `PyMethodDef` block, I think it's clearer to have the final `}` on its own line so that it's easy to see where this array ends.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> +#include <Python.h>
* Should `#define PY_SSIZE_T_CLEAN` on the previous line. See https://docs.python.org/3/c-api/arg.html#strings-and-buffers
* Should add a comment that Python.h must be included before any other includes as noted in https://docs.python.org/3/c-api/intro.html#include-files

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +#include "encoding_method.hpp"
Should be the first include because:

* That's what the style guide dictates.
* That will cause `Python.h` to be included before any other includes.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> + * Given the reference timestamp, the timestamp format, and the time zone,
* In each of these methods, could we omit mentioning the arguments in the method's description since we mention them in the description for `args`?
* Use command form for method descriptions.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> + * @param args, the reference timestamp, the timestamp format, and the time
In each of these methods, don't need a comma after `args`.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> + * @return python bytearray that contains the encoded preamble
Nits:
```suggestion
 * @return A Python byte array containing the encoded preamble
```

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> + * @return python bytearray that contains the encoded message
It also contains the timestamp delta, right?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> + * @return python bytearray that contains the encoded message
Copy paste error?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> +namespace clp_ffi_py::encoder::four_byte_encoding {
Style guide dictates that each namespace gets its own directory, so this should be in an `encoder` directory.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
> +#ifndef CLP_PY_ENCODING_METHOD
```suggestion
#ifndef CLP_FFI_PY_ENCODING_METHOD
```

2023-06-04 18:28 UTC, kirkrodrigues commented on LICENSE
> +   Copyright 2023 YScope Inc.
If you read from line 178, this paragraph is describing how the Apache License should be applied to a piece of work. E.g., if you wanted to apply the Apache license to a file, you wouldn't paste this entire file into the header of your file; instead, you would copy from line 189 to 201 and then modify the boilerplate values. For an example, see [here](https://github.com/openstack/nova/blob/master/nova/cache_utils.py).

So it's incorrect to change line 189 from the boilerplate value that it had.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.hpp
Filename should be `encoding_methods` (plural) right?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +#include <chrono>
Necessary?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/ErrorMessage.hpp
> +namespace clp_ffi_py::ErrorMessage {
* Technically namespaces should be named with snake case.
* It might be more intuitive to call this `error_messages` (plural)

2023-06-04 18:28 UTC, kirkrodrigues commented on .clang-format
> +ContinuationIndentWidth: 8
Let's add `InsertNewlineAtEOF: true`

2023-06-04 18:28 UTC, kirkrodrigues commented on .clang-format
> +AccessModifierOffset: -4
Let's add `AlignAfterOpenBracket: AlwaysBreak`

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +PyObject* encode_preamble (PyObject* self, PyObject* args) {
Can wrap unused parameters with `Py_UNUSED`.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +        PyArg_ParseTuple(args, "Lss", &ref_timestamp, &input_timestamp_format, &input_timezone)) {
Can we use `s#` for the strings? Similarly, we can use the `#` variant in the other methods.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +        PyErr_SetString(PyExc_RuntimeError, clp_ffi_py::ErrorMessage::arg_parsing_error);
The [docs](https://docs.python.org/3/c-api/intro.html#exceptions) suggest that:
* the API methods will throw a Python exception on failure and we should not throw our own exception since that will overwrite the already thrown exception.
* on exception, we should return `NULL` (`nullptr`) or `-1` depending on the method's return type.

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +        PyErr_SetString(PyExc_NotImplementedError,
Why `PyExc_NotImplementedError` instead of something like `PyExc_ValueError`?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +            PyByteArray_FromStringAndSize(reinterpret_cast<char*>(ir_buf.data()), ir_buf.size());
Use clp's `size_checked_pointer_cast`

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +    PyObject* output_bytearray =
Nit: Use `auto` or you could return the function's return value directly

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +    ir_buf.reserve(input_buffer.len * 2);
Can we add a comment explaining why we do this?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/encoding_method.cpp
> +        PyBuffer_Release(&input_buffer);
If we decide to stick with `y*`, it's probably beneficial to use a `unique_ptr` with a custom deleter like what we do in [`clp-ffi-java`](https://github.com/y-scope/clp-ffi-java/blob/main/src/main/cpp/libclp_ffi_java/JavaPrimitiveArrayElementsDeleter.cpp).

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +        PyModuleDef_HEAD_INIT, "CLPFourByteEncoder", NULL, -1, EncoderMethods};
* Let's define a module docstring.
* `-1` means the module has global state, right? So should we set it to `0` instead?

2023-06-04 18:28 UTC, kirkrodrigues commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +static struct PyModuleDef clp_four_byte_encoder = {
Don't need the `struct`

2023-06-04 18:52 UTC, kirkrodrigues requested changes
* Let's add the `.clang-tidy` config from log-surgeon.
* I haven't reviewed the "packaging" (GitHub action, README, etc.) files very carefully. I will when we're closer to finishing the PR.

2023-06-04 18:52 UTC, kirkrodrigues commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +PyMODINIT_FUNC PyInit_CLPFourByteEncoder (void) {
Do we need the `void`?

2023-06-04 18:52 UTC, kirkrodrigues commented on src/clp_ffi/ErrorMessage.hpp
> +constexpr char out_of_memory_error[] = "Failed to allocate memory.";
Unused?

2023-06-04 18:52 UTC, kirkrodrigues commented on src/clp_ffi/ErrorMessage.hpp
> +constexpr char timestamp_error[] = "Timestamp delta > signed int32 currently unsupported";
Using specific errors based on the IR-encoding method implementations does put a burden on this library to constantly stay up-to-date with the implementations of the IR encoding methods. A better option is probably to use exceptions within the IR encoding methods and return error strings that way. So personally, I would keep these errors generic for now until such time someone improves the IR encoding methods (an error with no details is better than an error with incorrect details).

2023-06-04 18:52 UTC, kirkrodrigues commented on README.md
> +   `python -m venv venv; .  ./venv/bin/activate`
Nit: Extra space after `.`

2023-06-04 18:52 UTC, kirkrodrigues commented on setup.py
> +    version="0.0",
Seems redundant to specify the version and description here (since it's already in the toml). Can we get rid of it?

2023-06-05 21:17 UTC, LinZhihao-723 commented on src/clp_ffi/clp_four_byte_encoder.cpp
> +        {NULL, NULL, 0, NULL}};
1. I would prefer using {nullptr, nullptr, 0, nullptr} to indicate the end of the method table explicitly.
2. the position of "}" is auto formatted by clang-format

2023-06-05 22:43 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.hpp
> + * @return python bytearray that contains the encoded message
Yes, added

2023-06-05 22:44 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.hpp
> + * @return python bytearray that contains the encoded message
Solved

2023-06-06 00:18 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.cpp
> +#include <chrono>
Removed

2023-06-06 00:42 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.cpp
> +        PyErr_SetString(PyExc_RuntimeError, clp_ffi_py::ErrorMessage::arg_parsing_error);
I will remove the error string and return nullptr instead.

2023-06-06 02:16 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.cpp
> +        PyBuffer_Release(&input_buffer);
let's use y# so we don't have to worry about memory manage.

2023-06-06 02:22 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.cpp
> +    ir_buf.reserve(input_buffer.len * 2);
"To avoid the frequent expansion of ir_buf, allocate sufficient space in advance"

2023-06-06 02:26 UTC, LinZhihao-723 commented on src/clp_ffi/ErrorMessage.hpp
> +constexpr char out_of_memory_error[] = "Failed to allocate memory.";
Yes, this one is used for later PR. It shouldn't be added at this point yet.

2023-06-06 03:41 UTC, LinZhihao-723 commented on setup.py
> +    version="0.0",
yes, this can be removed.

2023-06-07 21:38 UTC, LinZhihao-723 commented on src/clp_ffi/encoding_method.cpp
> +        PyErr_SetString(PyExc_NotImplementedError,
If the error happens, it's because the delta range is not handled. The current CLP logging library is returning NotImplemented.

2023-06-13 00:15 UTC, closed without merging