Update the CLP dependency to the lastest main branch commit
y-scope/clp-ffi-py pull request #29
Opened 2023-11-01 03:05 UTC by LinZhihao-723

# Description
Update the CLP dependency to use the latest features implemented in the CLP core. This includes:
1. Use `BufferReader` to decode log events
2. Add protocol version validation when decoding the metadata to ensure the input ir stream is supported with the current library version.

# Validation performed
1. Passed all the unit tests.
2. Passed all the C++ linters.

2023-11-05 21:14 UTC, kirkrodrigues requested changes

2023-11-05 21:14 UTC, kirkrodrigues commented on MANIFEST.in
> +recursive-include src/clp/components/core/src *.inc
You no longer need the line above

Also, to make things consistent, do you want to do the following?
* Rename `src/clp_ffi_py/utils.tpp` to `.inc`
* Change the `clp_ffi_py *.tpp` rule below to `.inc`

2023-11-05 21:14 UTC, kirkrodrigues commented on src/clp_ffi_py/ir/native/decoding_methods.cpp
> +                            "Unrecognized return code %d with version value %s",
```suggestion
                            "Unrecognized return code %d with version: %s",
```

2023-11-05 21:14 UTC, kirkrodrigues commented on src/clp_ffi_py/ir/native/decoding_methods.cpp
> +                    );
Missing a `break`?

2023-11-06 05:18 UTC, LinZhihao-723 commented on MANIFEST.in
> +recursive-include src/clp/components/core/src *.inc
True, I've renamed .tpp to `.inc` inside `clp_ffi_py` to make them consistent.

2023-11-06 05:23 UTC, kirkrodrigues approved these changes

2023-11-06 23:35 UTC, merged