Add Taskfile to build package; Refactor docs tasks.
y-scope/clp-ffi-py pull request #46
Opened 2024-03-14 19:18 UTC by kirkrodrigues

# Description

This PR:
* Adds a [Taskfile](https://taskfile.dev/usage/) to make it easier to build clp_ffi_py
* Refactors the docs Taskfile so that it can be called from the main Taskfile.
* Applies our latest guidelines for Taskfiles to the docs tasks.

NOTE: This PR requires task v3.35.1 for the latest bug fixes.

# Validation performed

* Validated building each artifact from a clean state:

  ```bash
  task clean && task
  task clean && task wheel
  task clean && task docs:site
  ```

* Validated repeated builds of each artifact-generating task did not result in the artifact being regenerated:

  ```bash
  task clean && task wheel && task wheel
  task clean && task docs:site && task docs:site
  ```

* Validated that after running `task docs:site`, changing any of the following files triggered a rebuild of just the docs:
  * `docs/conf/conf.py`
  * `docs/src/index.md`
  * `docs/tasks.yml`
* Validated that after running `task wheel`, changing any of the following triggered a rebuild of the wheel:
  * `clp_ffi_py/__init__.py`
  * `src/clp` (the version of the clp submodule)
  * `src/clp_ffi_py/error_messages.hpp`
  * `Taskfile.yml`
* Validated that after running `task docs:site`, changing any of the following files from the previous step triggered a rebuild of the wheel and the docs.
* Validated `task clean && task docs:serve` built and served the site.

2024-03-14 19:58 UTC, kirkrodrigues commented
Workflow failures unrelated to the present PR. They'll be addressed in another PR.

2024-03-14 20:52 UTC, junhaoliao approved these changes
It seems we do not checksum all `build/dist` artifacts. e.g.,
```shell
rm -f build/dist/*.tar.gz
task # does not trigger `wheel` rebuild
```

Just want to make sure whether that is intended as I understand the `build/dist/*.whl` file is the final packaged file. Approved assuming that is intended.

2024-03-14 20:54 UTC, junhaoliao commented
Title: ?
```
Add a main `Taskfile` to make it easier to build clp_ffi_py; Refactor the docs `Taskfile` to make it callable by the main Taskfile. (#46)
```

2024-03-14 21:07 UTC, junhaoliao requested changes
In fact, hashing of the `*.whl` file does not seem correctly handled. I modified the magic number `PK` of `build/dist/clp_ffi_py-0.0.10-cp310-cp310-linux_x86_64.whl` and running the `task` command did not rebuild the task.

2024-03-14 21:07 UTC, junhaoliao commented on Taskfile.yml
> +        python3 -m build --outdir "{{.OUTPUT_DIR}}"
```suggestion
        python3 -m build --outdir "{{.OUTPUT_DIR}}"
      # Checksum the generated files (this command must be last)
      - |-
        cd "{{.OUTPUT_DIR}}"
        tar cf - {{.CHECKSUM_TAR_BASE_ARGS}} . | md5sum > "{{.CHECKSUM_FILE}}"
```

2024-03-14 21:07 UTC, junhaoliao commented on Taskfile.yml
> +      - "{{.OUTPUT_DIR}}/*.whl"
```suggestion
    status:
      - "test -f '{{.CHECKSUM_FILE}}'"
      - >-
        diff
        <(cd '{{.OUTPUT_DIR}}' && tar cf - {{.CHECKSUM_TAR_BASE_ARGS}} . | md5sum)
        "{{.CHECKSUM_FILE}}"
```

2024-03-14 21:20 UTC, kirkrodrigues commented
> It seems we do not checksum all build/dist artifacts. e.g.,

I did intentionally leave out the `.tar.gz`, but that is probably not a good idea since the `.tar.gz` can be used to build the package from source. Added the `.tar.gz`.

> In fact, hashing of the *.whl file does not seem correctly handled.

Huh, strange. I would've expected `task` to checksum the file properly by itself. Anyway, switched to the explicit md5 checksum.

2024-03-15 15:05 UTC, junhaoliao approved these changes
Looks good.

2024-03-15 15:09 UTC, merged