Adds FourByteEncoder class to hold all the four byte encoding methods
y-scope/clp-ffi-py pull request #5
Opened 2023-07-20 04:14 UTC by LinZhihao-723

# Description
Add a new Python class `FourByteEncoder` to hold all the four byte encoding methods as static members, and thus providing a better code organization.

# Validation performed
1. Passed all the existing unit tests.
2. Added new tests for FourByteEncoder class.
3. Passed both cpp and Python linting tools.

2023-07-20 04:20 UTC, LinZhihao-723 commented
The following will be the results of `help`:
```
class FourByteEncoder(builtins.object)
     |  Namespace for all CLP encoding methods.
     |  
     |  Methods encode bytes from the log record to create a CLP log message. This class should never be instantiated since it only contains static methods.
     |  
     |  Static methods defined here:
     |  
     |  encode_message(msg)
     |      Encodes the log `msg` using the 4-byte encoding.
     |      :param msg: Log message to encode.
     |      :raises NotImplementedError: If the log message failed to encode.
     |      :return: The encoded message.
     |  
     |  encode_message_and_timestamp_delta(timestamp_delta, msg)
     |      Encodes the log `msg` along with the timestamp delta using the 4-byte encoding.
     |      :param timestamp_delta: Timestamp difference in milliseconds between the current log message and the previous log message.
     |      :param msg: Log message to encode.
     |      :raises NotImplementedError: If the log message failed to encode, or the timestamp delta exceeds the supported size.
     |      :return: The encoded message and timestamp.
     |  
     |  encode_preamble(ref_timestamp, timestamp_format, timezone)
     |      Creates the encoded CLP preamble for a stream of encoded log messages using the 4-byte encoding.
     |      :param ref_timestamp: Reference timestamp used to calculate deltas emitted with each message.
     |      :param timestamp_format: Timestamp format to be use when generating the logs with a reader.
     |      :param timezone: Timezone in TZID format to be use when generating the timestamp from Unix epoch time.
     |      :raises NotImplementedError: If metadata length too large.
     |      :return: The encoded preamble.
     |  
     |  encode_timestamp_delta(timestamp_delta)
     |      Encodes the timestamp using the 4-byte encoding.
     |      :param timestamp_delta: Timestamp difference in milliseconds between the current log message and the previous log message.
     |      :raises NotImplementedError: If the timestamp failed to encode.
     |      :return: The encoded timestamp.
```

2023-07-23 04:35 UTC, davidlion requested changes

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/modules/ir.cpp
> +extern "C" {
```suggestion
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/modules/ir.cpp
> +}
```suggestion
```

Matches removal of opening `extern "C"` block on line 24.

2023-07-23 04:35 UTC, davidlion commented on tests/test_clpir.py
> +    Class for testing clp_ffi_py.CLPIR.FourByteEncoder.
```suggestion
    Class for testing clp_ffi_py.ir.FourByteEncoder.
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.hpp
> +     * This class provides a Python level namespace for CLP 4-byte encoding methods.
```suggestion
     * This class provides a Python level namespace for CLP 4-byte encoding
     * methods.
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.hpp
> +     * incorporates this type as a Python object into the py_module module.
```suggestion
     * incorporates this type as a Python object into the module, py_module.
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +
```suggestion
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +
```suggestion

#include <clp_ffi_py/ir/encoding_methods.hpp>
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +#include "encoding_methods.hpp"
```suggestion
```

Added above without relative path.

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +        "Namespace for all CLP encoding methods.\n\n"
```suggestion
        "Namespace for all CLP four byte IR encoding methods.\n\n"
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +// NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays, cppcoreguidelines-pro-type-*-cast)
```suggestion
// NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays, cppcoreguidelines-pro-type-const-cast)
```

2023-07-23 04:35 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.cpp
> +// NOLINTEND(cppcoreguidelines-avoid-c-arrays, cppcoreguidelines-pro-type-*-cast)
```suggestion
// NOLINTEND(cppcoreguidelines-avoid-c-arrays, cppcoreguidelines-pro-type-const-cast)
```

2023-07-23 04:35 UTC, davidlion commented on tests/test_clpir.py
> +        """
I think we can just rename this test (and rewrite the doc string accordingly) to be explicitly for testing whether "`encode_message_and_timestamp_delta` is consistent with the addition of `encode_message` and `encode_timestamp_delta`".

We can move the TODO and comments on general encoding tests to the class doc string.

2023-07-23 05:03 UTC, davidlion requested changes

2023-07-23 05:03 UTC, davidlion commented on tests/test_clpir.py
> +        consistent with the combine of encode_message and
```suggestion
        consistent with the conbination of encode_message and
```

2023-07-23 05:03 UTC, davidlion commented on src/clp_ffi_py/ir/PyFourByteEncoder.hpp
> +     * incorporates this type as a Python object into the py_module.
```suggestion
     * incorporates this type as a Python object into py_module.
```

2023-07-23 18:23 UTC, kirkrodrigues requested changes
* Minor fixes.
* You still have an instance of "clp_ir.cpp" in `clp_ffi_py/ir/encoding_methods.hpp`.

2023-07-23 18:23 UTC, kirkrodrigues commented on src/clp_ffi_py/ir/PyFourByteEncoder.hpp
> +#define CLP_FFI_PY_PyFourByteEncoder_HPP
```suggestion
#ifndef CLP_FFI_PY_PYFOURBYTEENCODER_HPP
#define CLP_FFI_PY_PYFOURBYTEENCODER_HPP
```

2023-07-23 18:23 UTC, kirkrodrigues commented on src/clp_ffi_py/ir/PyFourByteEncoder.hpp
> +     */
```suggestion
/**
 * This class provides a Python-level namespace for CLP 4-byte IR encoding
 * methods.
 */
class PyFourByteEncoder {
```

2023-07-23 18:46 UTC, kirkrodrigues approved these changes

2023-07-23 18:53 UTC, davidlion approved these changes

2023-07-23 19:08 UTC, merged