Add support for Substring and Full string wildcard queries.
y-scope/clp-ffi-py pull request #62
Opened 2024-06-03 17:40 UTC by LinZhihao-723

# References

# Description

As discussed in PR #27, users usually want the query to be automatically surrounded with wildcard `*` to match a substring. This PR implements such a query in a way we discussed and agreed on in PR #27. Essentially, this PR contains the following changes:
- Redesign `WildcardQuery` classes. `WildcardQuery` is now marked as deprecated. Instead, users should use its derived class `SubstringWildcardQuery` and `FullStringWildcardQuery` to define a wildcard query. When using `SubstringWildcardQuery`, `*` prefix and postfix will be automatically added to match a substring.
- Redesign `QueryBuilder` to change the method's signature of `add_wildcard_query`. It's taking a `WildcardQuery` class instead of a string and a boolean argument. The old signature can still be called but it is marked as deprecated.

We can support substring matches without breaking existing user code with the above implementations. In the future, we should also do the following cleanup:
- Formally remove the old signature of `add_wildcard_query`
- Make `WildcardQuery` as an abstract base class
- Close PR #27

# Validation performed

- All unit tests passed
- Add unit tests to cover deprecated functions
- CI passed, successfully built and tested across all the supported platforms and Python versions

2024-06-10 19:15 UTC, davidlion requested changes
Improve `add_wildcard_query`

2024-06-10 19:15 UTC, davidlion commented on clp_ffi_py/ir/query_builder.py
> +    def add_wildcard_query(self, *args: Tuple[Any, ...], **kwargs: Dict[str, Any]) -> QueryBuilder:
As discussed lets drop `no_type_check` and lets try a different approach.

2024-06-10 23:50 UTC, davidlion approved these changes
Lets change the title + commit message to something more direct like:
`Add more explicit interface to differentiate substring and full-string wildcard queries. (#62).`

2024-06-11 00:44 UTC, LinZhihao-723 commented
> Lets change the title + commit message to something more direct like: `Add more explicit interface to differentiate substring and full-string wildcard queries. (#62).`

The commit msg lgtm, thx!

2024-06-11 00:45 UTC, merged