Update to the latest clp submodule commit.
y-scope/clp-ffi-py pull request #66
Opened 2024-07-04 22:20 UTC by LinZhihao-723

# References

# Description

This PR updates to the latest clp commit. It contains the following changes:
1. Update to the latest IR deserialization procedure. Tags will be deserialized first before deserializing the actual packet. Notice that UTC offset deserialization is not yet supported. It will be added in the future PR.
2. Update the include path, so that src files include `<clp/header.hpp>` instead of `<clp/components/core/src/clp/header.hpp>`

# Validation performed

Workflow passed (lint, build, and unit testing).

2024-07-04 22:21 UTC, LinZhihao-723 commented on src/clp_ffi_py/ir/native/decoding_methods.cpp
> + */
This part of comments adapts to our latest guideline, where the comments are also 100 char length. I will send a PR after this one to update the rest of comments.

2024-07-05 04:30 UTC, davidlion requested changes

2024-07-05 04:30 UTC, davidlion commented on src/clp_ffi_py/ir/native/decoding_methods.cpp
> + * ignored. If it is set to true, incomplete stream error
```suggestion
 * ignored. If it is set to true, incomplete stream error.
```

2024-07-05 17:28 UTC, davidlion approved these changes

2024-07-05 17:28 UTC, merged